# fly.toml app configuration file generated for abdi-two-week-project-frosty-waterfall-7654 on 2025-09-17T18:04:53+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'abdi-two-week-project-frosty-waterfall-7654'
primary_region = 'arn'

[build]
  dockerfile = './Dockerfile'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
